name: Tests

on: [push, pull_request]

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  unit_tests:
    name: build windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest]

    steps:
    - name: Add msbuild to PATH (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install NuGet
      uses: nuget/setup-nuget@v1.0.5

    - name: Checkout Source
      uses: actions/checkout@v2.3.4

    - name: Restore NuGet Packages
      run: nuget restore Duplicati.sln
    #---------
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish
      #-----https://elanderson.net/2020/06/github-use-actions-to-publish-artifacts/
    - name: Install Additional Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install gtk-sharp2

    - name: Build Duplicati (Windows)
      if: matrix.os == 'windows-latest'
      run: msbuild -p:Configuration=Release .\Installer\Windows\build-msi.bat   #Duplicati.sln,to path mpainei kai me " "
      

    - name: dl
      uses: actions/download-artifact@v2



