name: Tests

on: [push, pull_request]

env:
  build_directory: "Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release"

jobs:
  unit_tests:
    name: build windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest,ubuntu-latest]

    steps:
    - name: Add msbuild to PATH (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install NuGet
      uses: nuget/setup-nuget@v1.0.5

    - name: Checkout Source
      uses: actions/checkout@v2.3.4

    - name: Restore NuGet Packages
      run: nuget restore Duplicati.sln
  
    - name: Install Additional Dependencies 
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install gtk-sharp2
      
    - name: Install .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install dependencies
      run: dotnet restore Duplicati.sln
      
    - name: Build
      run: dotnet build ".\Installer\Windows\build-msi.bat"  --configuration Release --no-restore  #Duplicati.sln
      #run: dotnet build ${{ github.workspace }}/src/WebApp1/WebApp1.csproj --configuration Release --no-restore


   # - name: Publish
   #   run: dotnet publish Duplicati.sln
      

   # - name: Build Duplicati (Windows)
   #   if: matrix.os == 'windows-latest'
   #   run: msbuild -p:Configuration=Release Duplicati.sln #  #to path mpainei kai me ""  .\Installer\Windows\build-msi.bat
      

    #- name: download_artifacts #diko mou
   #   uses: actions/download-artifact@v2 #




